/**
 * Multi-chart split grid (platform feature). The generic split tree is engine-owned and
 * headless-tested; this browser host mirrors it into flex DOM and owns one full `create_chart`
 * instance per leaf cell (its own
 * scales, series, chart type, and drawing primitives — splitting never shares state).
 *
 * Commercial limits and usage metering stay here at the host boundary; the shared chart engine
 * knows nothing about subscriptions, billing, or tiers.
 */

// The wasm glue is generated by `wasm-pack` into ../pkg (see `bun run build:wasm`).
// @ts-ignore -- pkg is a build artifact, present after build:wasm
import { AerisWorkspace } from "../pkg/aeris_charts_wasm.js";
import { create_chart } from "./index.js";
import { canonical_drawing_kind, ensure_init } from "./impl.js";
import { AerisChartsError } from "./errors.js";
import { DEFAULT_SHORTCUTS, install_shortcuts } from "./shortcuts.js";
import type { shortcut_action } from "./shortcuts.js";
import { default_theme_name, theme_palette } from "./theme.js";
import style_tokens from "../../../crates/aeris_charts_core/style_tokens.json";
import type {
  chart_api,
  chart_options,
  chart_state,
  deep_partial,
  drawing_kind,
  drawing_options,
} from "./types.js";

/** `horizontal` places the two charts side by side; `vertical` stacks them. */
export type split_direction = "horizontal" | "vertical";

export type workspace_layout =
  | { kind: "cell"; id: number }
  | {
      kind: "split";
      direction: split_direction;
      ratio: number;
      a: workspace_layout;
      b: workspace_layout;
    };

export interface workspace_cell_state_v1 {
  stable_cell_id: number;
  /** Opaque host-owned identity (symbol/instrument key); aeris_charts never interprets it. */
  host_chart_identity?: string;
  chart_state: chart_state;
}

/** Host-storable layout plus each chart's independently versioned persistence document. */
export interface chart_workspace_state_v1 {
  schema: "aeris_charts-workspace";
  schema_version: 1;
  layout: workspace_layout;
  active_cell?: number;
  cells: workspace_cell_state_v1[];
}

/** Host-owned usage snapshot, emitted on every topology change. */
export interface grid_usage {
  chart_count: number;
  split_count: number;
  elapsed_seconds: number;
  cells: { id: number; age_seconds: number }[];
}

export interface grid_cell {
  readonly id: number;
  readonly chart: chart_api;
  /** The cell's flex slot; per-cell chrome (buttons, legends) attaches here. */
  readonly element: HTMLDivElement;
  readonly created_at: number;
  /** Optional opaque host identity included by workspace export/restore. */
  readonly host_chart_identity: string | null;
  set_host_chart_identity(identity: string | null): void;
  /**
   * Split this cell in two: the existing chart keeps its state in the first half and a fresh
   * chart (same base options) is created in the second. Resolves to the NEW cell, or `null`
   * when the host cap or veto rejects the split.
   */
  split(direction: split_direction): Promise<grid_cell | null>;
  /** Remove this cell: its sibling subtree absorbs the freed space (last cell refuses). */
  remove(): boolean;
}

export interface chart_grid_options {
  /** Base options for every chart the grid creates (the first cell and each split half). */
  chart_options?: deep_partial<chart_options>;
  /** Host-owned hard cap on live charts; `null`/absent = unlimited. */
  max_charts?: number | null;
  /** Veto hook evaluated before topology mutation: return `false` to reject. */
  on_split_request?: (next_count: number) => boolean;
  /** Usage signal sink: called with a fresh engine snapshot on every split/remove. */
  on_usage?: (usage: grid_usage) => void;
  /** Optional heartbeat (ms) re-emitting usage so time-based meters stay current. */
  usage_heartbeat_ms?: number;
  /** The split-divider line color. `null`/absent (the default) FOLLOWS the first chart's
   *  axis border color — the divider is axis chrome, so it tracks the same token (theme and
   *  explicit border changes); an explicit string pins it. */
  divider_color?: string | null;
  /** Split shortcuts: `true` uses the engine defaults (shortcuts.ts `DEFAULT_SHORTCUTS`), an
   *  object overrides individual combos (e.g. `{ "grid.split_vertical": "ctrl+shift+x" }`),
   *  `false` disables. Default `true` — splitting is native grid behavior; platforms re-key
   *  rather than enable. Keys never fire while typing in a field. */
  shortcuts?: boolean | Partial<Record<shortcut_action, string>>;
  /** Fired for every cell created by a split (button or shortcut path): the platform's hook
   *  to seed/configure the fresh chart (data, theme, chrome). */
  on_cell_added?: (cell: grid_cell) => void;
  /** Restore a fresh grid from generic topology plus composed chart persistence V1 documents. */
  initial_state?: chart_workspace_state_v1;
  /** Fired for every restored cell after its Aeris chart state has been installed. */
  on_cell_restored?: (cell: grid_cell) => void;
}

export interface chart_grid {
  cells(): grid_cell[];
  chart_count(): number;
  usage(): grid_usage;
  set_max_charts(n: number | null): void;
  /** Pin a divider color, or pass `null` to re-enter follow mode (divider = axis border). */
  set_divider_color(color: string | null): void;
  /** The active cell (the last one pointer-pressed) — the target of the split shortcuts. */
  active_cell(): grid_cell;
  /** Explicitly activate a live cell by stable identity (toolbar/programmatic routing). */
  set_active_cell(cell: grid_cell): void;
  /** Arm/disarm the drawing tool on the active chart; the grid migrates an armed tool on focus. */
  set_drawing_tool(tool: drawing_kind | null, options?: Partial<drawing_options>): void;
  active_drawing_tool(): drawing_kind | null;
  set_drawing_tool_listener(listener: ((tool: drawing_kind | null) => void) | null): void;
  undo_drawing(): boolean;
  redo_drawing(): boolean;
  /** Reset the active chart's time and price views. */
  reset_view(): void;
  /** Compose layout and each cell's existing chart persistence V1 for host-owned storage. */
  export_state(): chart_workspace_state_v1;
  /** Maximize a cell to the full container (the others + dividers hide), or pass `null` to
   *  restore. Alt+click on a cell toggles this whenever the grid shows more than one chart. */
  maximize(cell: grid_cell | null): void;
  /** The maximized cell, or `null` when the grid is in its normal layout. */
  maximized_cell(): grid_cell | null;
  destroy(): void;
}

interface cell_record {
  id: number;
  slot: HTMLDivElement;
  host: HTMLDivElement;
  chart: chart_api;
  created_at: number;
  host_chart_identity: string | null;
  handle: handle_record;
}

// The public handle's `chart` is read-only externally but assigned once the chart resolves
// (the slot attaches and lays out first).
type handle_record = Omit<grid_cell, "chart"> & { chart: chart_api };

const FLEX_CHILD = "flex:1 1 0;min-width:0;min-height:0;position:relative;";
const now_seconds = () => Date.now() / 1000;

type layout_node = workspace_layout;
type split_layout_node = Extract<workspace_layout, { kind: "split" }>;

/**
 * @experimental Split-grid topology is public but not part of the frozen stable surface.
 * Create a grid holding a single chart in `container`. Split from there via `cell.split(...)`.
 * The container becomes a flex root the grid owns entirely.
 */
export async function create_chart_grid(
  container: HTMLElement,
  options: chart_grid_options = {},
): Promise<chart_grid> {
  await ensure_init(); // the workspace handle touches the wasm module directly
  container.style.display = "flex";
  container.style.overflow = "hidden";
  if (getComputedStyle(container).position === "static") {
    container.style.position = "relative";
  }

  const workspace = new AerisWorkspace(now_seconds());
  const initial_state = options.initial_state ?? null;
  if (
    initial_state !== null &&
    (initial_state.schema !== "aeris_charts-workspace" || initial_state.schema_version !== 1)
  ) {
    throw new AerisChartsError("persistence_version_error", "unsupported workspace state version");
  }
  if (initial_state !== null) {
    let layout_json: string;
    try {
      layout_json = JSON.stringify(initial_state.layout);
    } catch (error) {
      throw new AerisChartsError("serialization_error", `workspace layout is not JSON-serializable: ${error}`);
    }
    if (!workspace.restore_layout_json(layout_json)) {
      throw new AerisChartsError("invalid_data", "workspace layout is malformed or contains invalid cell identities");
    }
  }
  const layout_ids = JSON.parse(workspace.cell_ids_json()) as number[];
  const restored_cells = new Map<number, workspace_cell_state_v1>();
  if (initial_state !== null) {
    for (const cell of initial_state.cells) {
      if (restored_cells.has(cell.stable_cell_id)) {
        throw new AerisChartsError("invalid_data", `duplicate workspace cell ${cell.stable_cell_id}`);
      }
      restored_cells.set(cell.stable_cell_id, cell);
    }
    if (
      restored_cells.size !== layout_ids.length ||
      layout_ids.some((id) => !restored_cells.has(id))
    ) {
      throw new AerisChartsError("invalid_data", "workspace cells do not match the restored layout");
    }
    if (initial_state.active_cell !== undefined && !layout_ids.includes(initial_state.active_cell)) {
      throw new AerisChartsError("invalid_data", "workspace active cell is not present in the restored layout");
    }
  }
  const cells = new Map<number, cell_record>();
  const started_at = Date.now();
  let split_count = Math.max(0, layout_ids.length - 1);
  let max_charts = options.max_charts ?? null;
  let heartbeat: ReturnType<typeof setInterval> | null = null;
  let divider_color: string | null = options.divider_color ?? null;
  let active_id =
    initial_state?.active_cell !== undefined && layout_ids.includes(initial_state.active_cell)
      ? initial_state.active_cell
      : (layout_ids[0] as number);
  let workspace_tool: drawing_kind | null = null;
  let workspace_tool_options: Partial<drawing_options> | undefined;
  let workspace_tool_listener: ((tool: drawing_kind | null) => void) | null = null;

  /** Pointer id of an Alt+click maximize press. Its up/click must not reach any chart: the
   *  layout changes under the pointer, so the release can land on a different cell. */
  let swallowed_press: number | null = null;
  /** The compatibility click dispatched right after that release (if the browser sends one). */
  let swallow_click = false;
  const swallow_press_release = (e: Event) => {
    if (e.type === "click") {
      if (!swallow_click) return;
      swallow_click = false;
    } else {
      if (swallowed_press === null || (e as PointerEvent).pointerId !== swallowed_press) return;
      swallowed_press = null;
      if (e.type === "pointerup") {
        // A click follows in the same input task or not at all; never leak into a later press.
        swallow_click = true;
        setTimeout(() => { swallow_click = false; }, 0);
      }
    }
    e.preventDefault();
    e.stopPropagation();
  };
  for (const type of ["pointerup", "pointercancel", "click"]) {
    container.addEventListener(type, swallow_press_release, true);
  }

  const activate = (id: number) => {
    if (id === active_id || !cells.has(id)) return;
    const previous = cells.get(active_id);
    active_id = id;
    // Move only the globally armed tool template. Selection and all drawing state stay local.
    previous?.chart?.set_drawing_tool(null);
    if (workspace_tool !== null) {
      cells.get(id)?.chart?.set_drawing_tool(workspace_tool, workspace_tool_options);
    }
  };

  /** The divider line color: the pinned value, or the first chart's axis border color when
   *  following (default) — the divider is axis chrome and tracks the same token. */
  const resolve_divider_color = (): string => {
    if (divider_color !== null) return divider_color;
    const first = cells.values().next().value as cell_record | undefined;
    const border = (
      first?.chart.options() as { rightPriceScale?: { borderColor?: string } } | undefined
    )?.rightPriceScale?.borderColor;
    return border ?? theme_palette(default_theme_name).border;
  };

  const usage = (): grid_usage => {
    const now = Date.now();
    return {
      chart_count: cells.size,
      split_count,
      elapsed_seconds: Math.max(0, now - started_at) / 1000,
      cells: [...cells.values()].map((cell) => ({
        id: cell.id,
        age_seconds: Math.max(0, now - cell.created_at) / 1000,
      })),
    };
  };
  const emit_usage = () => options.on_usage?.(usage());

  /** The live divider elements (rebuilt by `reconcile`), repainted when the follow-source
   *  chart's options change (the axis border token is live, not sampled once). */
  const dividers = new Set<{ el: HTMLDivElement; horizontal: boolean }>();
  /** Paint a divider's line as a solid strip snapped to the ABSOLUTE device-pixel grid:
   *  the canonical border width projected to at least one full device pixel — the same rule the
   *  engine axis and pane borders use. A CSS gradient band can't do this
   *  (its stop edges anti-alias at fractional positions into a washed-out 2px line), and a
   *  fractional transform re-samples the same way — so the strip is POSITIONED (never
   *  transformed) on an integer device boundary, re-measured at paint time and on restyle. */
  const paint_divider = (el: HTMLDivElement, horizontal: boolean) => {
    requestAnimationFrame(() => {
      if (!el.isConnected) return;
      const dpr = window.devicePixelRatio || 1;
      const device_w = Math.max(1, Math.floor(style_tokens.border_width * dpr));
      const w = device_w / dpr; // css px per full-coverage device pixel(s)
      const rect = el.getBoundingClientRect();
      const edge = horizontal ? rect.left : rect.top;
      const size = horizontal ? rect.width : rect.height;
      const aligned_dev = Math.round((edge + size / 2) * dpr - device_w / 2);
      const offset = aligned_dev / dpr - edge;
      let inner = el.firstElementChild as HTMLDivElement | null;
      if (inner === null) {
        inner = document.createElement("div");
        el.appendChild(inner);
      }
      inner.style.cssText = horizontal
        ? `position:absolute;top:0;bottom:0;left:${offset}px;width:${w}px;background:${resolve_divider_color()};`
        : `position:absolute;left:0;right:0;top:${offset}px;height:${w}px;background:${resolve_divider_color()};`;
    });
  };
  /** Re-resolve and repaint every divider (axis border changed, or a pinned color was set). */
  const restyle_dividers = () => {
    for (const { el, horizontal } of dividers) paint_divider(el, horizontal);
  };

  /** The adjacent cell ids flanking a split node (its divider's left/top and right/bottom). */
  const edge_ids = (node: layout_node, side: "first" | "last"): number => {
    if (node.kind === "cell") return node.id as number;
    return edge_ids((side === "last" ? node.b : node.a) as layout_node, side);
  };

  /** The draggable split divider: a 5px hit area with a canonical-width visible rule,
   *  col/row cursor per direction. The visible line is a solid inner strip snapped to the
   *  device-pixel grid (see `paint_divider`), so it matches the canvas axis border's hairline
   *  under any DPR and any host-page `box-sizing` reset. Dragging adjusts the two sides' flex
   *  weights live and persists the final ratio engine-side on release. */
  const make_divider = (
    node: split_layout_node,
    horizontal: boolean,
    a_el: HTMLElement,
    b_el: HTMLElement,
  ): HTMLDivElement => {
    const div = document.createElement("div");
    div.className = "aeris_charts-grid-divider";
    div.style.cssText =
      "flex:0 0 5px;position:relative;z-index:4;touch-action:none;" +
      `cursor:${horizontal ? "col-resize" : "row-resize"};` +
      (horizontal ? "margin:0 -2px;" : "margin:-2px 0;");
    paint_divider(div, horizontal);
    dividers.add({ el: div, horizontal });
    div.addEventListener("pointerdown", (e) => {
      e.preventDefault();
      div.setPointerCapture(e.pointerId);
      const start_ratio = node.ratio ?? 0.5;
      const left_id = edge_ids(node.a as layout_node, "last");
      const right_id = edge_ids(node.b as layout_node, "first");
      const start_pos = horizontal ? e.clientX : e.clientY;
      const parent_size =
        (div.parentElement as HTMLElement).getBoundingClientRect()[horizontal ? "width" : "height"] || 1;
      let current = start_ratio;
      const on_move = (ev: PointerEvent) => {
        const delta = ((horizontal ? ev.clientX : ev.clientY) - start_pos) / parent_size;
        current = Math.min(0.95, Math.max(0.05, start_ratio + delta));
        // Live: re-weight the two sides without rebuilding the layout (the divider being
        // dragged must stay put); the engine persists the ratio on release.
        a_el.style.flexGrow = String(current);
        b_el.style.flexGrow = String(1 - current);
      };
      const on_up = () => {
        div.removeEventListener("pointermove", on_move);
        div.removeEventListener("pointerup", on_up);
        div.removeEventListener("pointercancel", on_up);
        if (current !== start_ratio) {
          workspace.resize_between(left_id, right_id, current - start_ratio);
          reconcile();
        }
      };
      div.addEventListener("pointermove", on_move);
      div.addEventListener("pointerup", on_up);
      div.addEventListener("pointercancel", on_up);
    });
    return div;
  };

  const make_slot = (): { slot: HTMLDivElement; host: HTMLDivElement } => {
    const slot = document.createElement("div");
    slot.style.cssText = FLEX_CHILD;
    const host = document.createElement("div");
    host.style.cssText = "position:absolute;inset:0;";
    slot.appendChild(host);
    return { slot, host };
  };

  const prepare_cell = (id: number, host_chart_identity: string | null): cell_record => {
    const { slot, host } = make_slot();
    const record: cell_record = {
      id,
      slot,
      host,
      chart: null as unknown as chart_api,
      created_at: Date.now(),
      host_chart_identity,
      handle: null as unknown as grid_cell,
    };
    record.handle = {
      id,
      chart: null as unknown as chart_api,
      element: slot,
      created_at: record.created_at,
      get host_chart_identity() {
        return record.host_chart_identity;
      },
      set_host_chart_identity: (identity) => {
        record.host_chart_identity = identity;
      },
      split: (direction) => split(record, direction),
      remove: () => remove(record),
    } as handle_record;
    cells.set(id, record);
    // The last pointer-pressed cell is the ACTIVE one — the target of the split shortcuts.
    // Alt+primary-click toggles the cell's full-container maximize in a multi-chart layout.
    // CAPTURE phase, and the whole press is consumed: the chart never sees it, so the shortcut
    // cannot also pan, select, or place a drawing anchor. Alt carries no chart gesture meaning.
    slot.addEventListener("pointerdown", (e) => {
      activate(id);
      // A new press always starts clean, even if the last swallowed release left the grid.
      swallowed_press = null;
      swallow_click = false;
      if (e.altKey && e.button === 0 && (cells.size > 1 || maximized_id !== null)) {
        e.preventDefault();
        e.stopPropagation();
        swallowed_press = e.pointerId;
        toggle_maximize(id);
      }
    }, true);
    return record;
  };

  const initialize_chart = async (
    record: cell_record,
    state?: chart_state,
  ): Promise<cell_record> => {
    const { id, host } = record;
    // The slot must be ATTACHED (real size) before the chart measures its container: a
    // detached host reads 0×0, the first fit packs at minimum spacing, and the later
    // auto-resize explodes the visible range.
    record.chart = await create_chart(host, { autoSize: true, ...options.chart_options });
    record.handle.chart = record.chart;
    if (state !== undefined) record.chart.import_state(state);
    record.chart.set_drawing_tool_listener((tool) => {
      if (id !== active_id) return;
      workspace_tool = tool;
      workspace_tool_listener?.(tool);
    });
    // The divider follows the first chart's axis border token live: any apply_options on any
    // cell (theme switch, explicit borderColor) repaints the dividers without a topology change.
    record.chart.subscribe_options_change(restyle_dividers);
    return record;
  };

  const add_chart = async (id: number): Promise<cell_record> => {
    const record = prepare_cell(id, null);
    reconcile();
    return initialize_chart(record);
  };

  /** Mirror the engine's layout tree into the DOM, reusing cell slots by id (chart DOM/state
   *  is never rebuilt — only the split wrappers are). */
  const reconcile = () => {
    // Maximized: mount ONLY the maximized slot at the container root, bypassing every split
    // wrapper (flexing the slot alone can never expand it past its ancestors' ratios — the
    // "maximized" cell would stay trapped in its quadrant while hidden cells left blank
    // holes). The other slots stay detached until restore.
    if (maximized_id !== null) {
      const record = cells.get(maximized_id);
      if (record !== undefined) {
        container.replaceChildren(record.slot);
        record.slot.style.display = "";
        record.slot.style.flex = "1 1 100%";
        return;
      }
      maximized_id = null; // the maximized cell was removed; fall through to the tree build
    }
    const build = (node: layout_node): HTMLElement => {
      if (node.kind === "cell") {
        const record = cells.get(node.id as number);
        if (!record) {
          throw new AerisChartsError("invalid_handle", `grid cell ${node.id} has no chart`);
        }
        record.slot.style.display = "";
        return record.slot;
      }
      const horizontal = node.direction === "horizontal";
      const ratio = node.ratio ?? 0.5;
      const div = document.createElement("div");
      div.style.cssText = `${FLEX_CHILD}display:flex;flex-direction:${horizontal ? "row" : "column"};`;
      const a_el = build(node.a as layout_node);
      const b_el = build(node.b as layout_node);
      a_el.style.flexGrow = String(ratio);
      b_el.style.flexGrow = String(1 - ratio);
      div.appendChild(a_el);
      div.appendChild(make_divider(node, horizontal, a_el, b_el));
      div.appendChild(b_el);
      return div;
    };
    const layout = JSON.parse(workspace.layout_json()) as layout_node;
    // The split wrappers (and their dividers) are rebuilt wholesale; cell slots are reused.
    dividers.clear();
    container.replaceChildren(build(layout));
  };

  /** The maximized cell id (full container), or `null` in the normal layout. */
  let maximized_id: number | null = null;
  /** Set (or clear) the maximized cell; clearing resets the slot's flex override and rebuilds
   *  the layout so the engine's split ratios win their flex weights back. */
  const set_maximized = (id: number | null) => {
    if (maximized_id !== null) {
      const previous = cells.get(maximized_id);
      if (previous !== undefined) previous.slot.style.flex = "";
    }
    maximized_id = id;
    reconcile();
  };
  /** Alt+click semantics: maximize the cell, or restore when it's already maximized. */
  const toggle_maximize = (id: number) => {
    set_maximized(maximized_id === id ? null : id);
  };

  const split = async (cell: cell_record, direction: split_direction): Promise<grid_cell | null> => {
    const next_count = cells.size + 1;
    if (max_charts !== null && next_count > max_charts) return null;
    if (options.on_split_request?.(next_count) === false) return null;
    const new_id = Number(workspace.split(cell.id, direction, now_seconds()));
    if (new_id < 0) return null; // unknown cell
    // A split drops the maximize state first: the new cell must be ATTACHED to measure its
    // host, and a maximized view mounts only the maximized slot (a detached host reads 0×0).
    if (maximized_id !== null) set_maximized(null);
    const created = await add_chart(new_id);
    split_count += 1;
    reconcile();
    // One hook for every split path (button or shortcut): the platform seeds the fresh cell.
    options.on_cell_added?.(created.handle);
    emit_usage();
    return created.handle;
  };

  const remove = (cell: cell_record): boolean => {
    if (!workspace.remove(cell.id)) return false; // unknown id or the last chart
    if (active_id === cell.id) {
      const next_id = (JSON.parse(workspace.cell_ids_json()) as number[])[0] as number;
      activate(next_id);
    }
    cell.chart.unsubscribe_options_change(restyle_dividers);
    cell.chart.set_drawing_tool_listener(null);
    cell.chart.remove();
    cell.slot.remove();
    cells.delete(cell.id);
    reconcile();
    emit_usage();
    return true;
  };

  if (initial_state === null) {
    await add_chart(layout_ids[0] as number);
  } else {
    // Prepare every stable slot before measuring any chart so the restored layout is complete
    // and every host has its real final flex size during chart construction.
    for (const id of layout_ids) {
      const restored = restored_cells.get(id) as workspace_cell_state_v1;
      prepare_cell(id, restored.host_chart_identity ?? null);
    }
    reconcile();
    try {
      for (const id of layout_ids) {
        const restored = restored_cells.get(id) as workspace_cell_state_v1;
        await initialize_chart(cells.get(id) as cell_record, restored.chart_state);
      }
      for (const id of layout_ids) options.on_cell_restored?.((cells.get(id) as cell_record).handle);
    } catch (error) {
      for (const cell of cells.values()) {
        if (cell.chart !== null) cell.chart.remove();
      }
      cells.clear();
      container.replaceChildren();
      container.style.display = "";
      container.style.overflow = "";
      throw error;
    }
  }
  reconcile();

  // A window resize or DPR change (moving across monitors) shifts every divider off the
  // device grid — repaint them so the line keeps full device-pixel coverage.
  const on_window_resize = () => restyle_dividers();
  window.addEventListener("resize", on_window_resize);

  /** Install the split shortcuts from the registry (shortcuts.ts): defaults, with any
   *  platform overrides merged in. */
  const detach_shortcuts =
    options.shortcuts === false
      ? null
      : install_shortcuts(
          (["grid.split_horizontal", "grid.split_vertical", "drawing.undo", "drawing.redo"] as const).map((action) => ({
            combo:
              (typeof options.shortcuts === "object" ? options.shortcuts[action] : undefined) ??
              DEFAULT_SHORTCUTS[action].combo,
            run: () => {
              const cell = cells.get(active_id);
              if (cell !== undefined && action.startsWith("grid.")) {
                void split(cell, action === "grid.split_horizontal" ? "horizontal" : "vertical");
              } else if (cell !== undefined) {
                if (action === "drawing.undo") cell.chart.undo_drawing();
                else cell.chart.redo_drawing();
              }
            },
          })),
        );

  if (options.usage_heartbeat_ms && options.usage_heartbeat_ms > 0) {
    heartbeat = setInterval(emit_usage, options.usage_heartbeat_ms);
  }
  emit_usage();

  return {
    cells: () =>
      (JSON.parse(workspace.cell_ids_json()) as number[]).map((id) => cells.get(id)!.handle),
    chart_count: () => workspace.chart_count(),
    usage,
    set_max_charts: (n) => {
      max_charts = n;
    },
    set_divider_color: (color) => {
      divider_color = color;
      reconcile();
    },
    active_cell: () => cells.get(active_id)!.handle,
    set_active_cell: (cell) => {
      const record = cells.get(cell.id);
      if (record?.handle !== cell) {
        throw new AerisChartsError("invalid_handle", "cell does not belong to this live grid");
      }
      activate(cell.id);
    },
    set_drawing_tool: (tool, tool_options) => {
      workspace_tool = tool === null ? null : canonical_drawing_kind(tool);
      if (tool_options !== undefined) workspace_tool_options = { ...tool_options };
      cells.get(active_id)!.chart.set_drawing_tool(tool, tool_options);
    },
    active_drawing_tool: () => workspace_tool,
    set_drawing_tool_listener: (listener) => {
      workspace_tool_listener = listener;
    },
    undo_drawing: () => cells.get(active_id)!.chart.undo_drawing(),
    redo_drawing: () => cells.get(active_id)!.chart.redo_drawing(),
    reset_view: () => cells.get(active_id)!.chart.reset_view(),
    export_state: () => ({
      schema: "aeris_charts-workspace",
      schema_version: 1,
      layout: JSON.parse(workspace.layout_json()) as workspace_layout,
      active_cell: active_id,
      cells: (JSON.parse(workspace.cell_ids_json()) as number[]).map((id) => {
        const cell = cells.get(id)!;
        return {
          stable_cell_id: id,
          ...(cell.host_chart_identity === null
            ? {}
            : { host_chart_identity: cell.host_chart_identity }),
          chart_state: cell.chart.export_state(),
        };
      }),
    }),
    maximize: (cell) => set_maximized(cell === null ? null : cell.id),
    maximized_cell: () => {
      const record = maximized_id === null ? undefined : cells.get(maximized_id);
      return record === undefined ? null : record.handle;
    },
    destroy: () => {
      if (heartbeat !== null) clearInterval(heartbeat);
      window.removeEventListener("resize", on_window_resize);
      for (const type of ["pointerup", "pointercancel", "click"]) {
        container.removeEventListener(type, swallow_press_release, true);
      }
      detach_shortcuts?.();
      for (const cell of cells.values()) {
        cell.chart.unsubscribe_options_change(restyle_dividers);
        cell.chart.set_drawing_tool_listener(null);
        cell.chart.remove();
      }
      cells.clear();
      dividers.clear();
      container.replaceChildren();
      container.style.display = "";
      container.style.overflow = "";
    },
  };
}
