/**
 * @aeristerminal/aeris-charts — public API.
 *
 * A thin, typed façade over the `aeris_charts_wasm` engine. It owns the browser-side concerns that the
 * engine deliberately leaves out: creating the stacked canvases (WebGPU/Canvas2D pane + package-owned
 * plugin overlay + Canvas2D axis/input overlay), the input-gesture recognizer, typed-array packing
 * of data at the boundary, and the chart/series/time-scale handle objects. All model, layout, and
 * rendering math lives in Rust.
 *
 * WebGPU device acquisition is async, so `create_chart` returns a Promise — the one deliberate
 * divergence from the reference's synchronous `createChart`.
 */

// The wasm glue is generated by `wasm-pack` into ../pkg (see `bun run build:wasm`). esbuild inlines
// it when bundling; the .wasm is fetched at runtime relative to the output bundle.
// @ts-ignore -- pkg is a build artifact, present after build:wasm
import { create_chart as wasm_create_chart } from "../pkg/aeris_charts_wasm.js";

export * from "./types.js";
export * from "./errors.js";
export * from "./theme.js";
export * from "./primitives.js";
export * from "./canvas_plugins.js";
export * from "./custom_series.js";
export * from "./feature_series.js";
export * from "./builtin_plugins.js";
export * from "./primitive_features.js";
export * from "./accessibility.js";
export * from "./offscreen.js";
export * from "./shortcuts.js";
export * from "./grid.js";
import { chart_impl } from "./impl.js";
import { ensure_init } from "./impl.js";
export { session_slot_times } from "./impl.js";
export { resample_boundaries } from "./impl.js";
import { enable_accessibility } from "./accessibility.js";
import type { accessibility_options } from "./accessibility.js";
import { default_theme_name, theme_options, theme_palette, type theme_name } from "./theme.js";
import { split_exchange_time_options } from "./time_zone.js";
import type { chart_api, chart_options, deep_partial, localization_options, tracking_mode_options } from "./types.js";

// ---------------------------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------------------------

/**
 * Pre-instantiate the wasm engine, optionally from an explicit URL. Only needed when the default
 * resolution (the `.wasm` shipped beside `dist/index.js`) doesn't apply — e.g. Vite's dev
 * pre-bundler (`import wasm_url from "@aeristerminal/aeris-charts/wasm?url"`). Call once,
 * before the first `create_chart`; later calls are no-ops.
 */
export function init_wasm(wasm_url?: string | URL): Promise<unknown> {
  return ensure_init(wasm_url);
}

/** Camel-case alias of {@link init_wasm}. */
export const initWasm = init_wasm;

/**
 * Create a chart inside `container`. Resolves once the rendering backend is ready and the first
 * frame is drawn. It provides a familiar `createChart`-style entry point and is asynchronous because
 * backend acquisition must complete first.
 */
export async function create_chart(
  container: HTMLElement,
  options?: deep_partial<chart_options>,
): Promise<chart_api> {
  await ensure_init();

  // Four stacked, absolutely-positioned canvases fill the container: dedicated WebGPU and
  // Canvas2D panes below the transparent plugin overlay (Phase C-e canvas primitives), below the
  // transparent axis/input overlay. A canvas cannot change context type, so keeping the fallback
  // pane warm is what makes device-loss failover possible without recreating the chart or moving
  // state out of the headless engine. The plugin overlay is plain package-owned DOM (no wasm
  // involvement): it never takes input (gestures live on the top overlay), and the package
  // paints it after each engine frame.
  const previous_container_position = container.style.position;
  const assigned_relative_position = getComputedStyle(container).position === "static";
  if (assigned_relative_position) {
    container.style.position = "relative";
  }
  const gpu_pane = document.createElement("canvas");
  const fallback_pane = document.createElement("canvas");
  const plugin_canvas = document.createElement("canvas");
  const overlay = document.createElement("canvas");
  // The visible keyboard surface is the chart-owned accessibility layer. Keep the input canvas
  // out of sequential navigation while preserving the pre-0.9 programmatic-focus shortcut path.
  overlay.tabIndex = -1;
  for (const c of [gpu_pane, fallback_pane, plugin_canvas, overlay]) {
    c.style.position = "absolute";
    c.style.inset = "0";
    c.style.width = "100%";
    c.style.height = "100%";
    c.style.display = "block";
    // The gesture controller derives `touch-action` from chart options before input begins.
  }
  plugin_canvas.style.pointerEvents = "none";
  overlay.style.cursor = "crosshair";
  container.appendChild(gpu_pane);
  container.appendChild(fallback_pane);
  container.appendChild(plugin_canvas);
  container.appendChild(overlay);

  const rect = container.getBoundingClientRect();
  const css_w = Math.max(rect.width, 1);
  const css_h = Math.max(rect.height, 1);
  const dpr = window.devicePixelRatio || 1;
  // Bootstrap the bitmap size so either pane backend configures; auto-resize (if enabled) or a
  // manual resize() will correct it.
  for (const c of [gpu_pane, fallback_pane, plugin_canvas, overlay]) {
    c.width = Math.max(1, Math.round(css_w * dpr));
    c.height = Math.max(1, Math.round(css_h * dpr));
  }

  const simulate_adapter_failure = (
    options as (deep_partial<chart_options> & {
      __simulate_webgpu_adapter_failure?: boolean;
      __force_webgpu_fallback_adapter?: boolean;
    }) | undefined
  )?.__simulate_webgpu_adapter_failure === true;
  const force_fallback_adapter = (
    options as (deep_partial<chart_options> & { __force_webgpu_fallback_adapter?: boolean }) | undefined
  )?.__force_webgpu_fallback_adapter === true;
  const initial_horizontal_domain = options?.initialPane?.horizontal_domain ?? { type: "financial_time" };
  const wasm = await wasm_create_chart(
    gpu_pane,
    fallback_pane,
    overlay,
    css_w,
    css_h,
    dpr,
    options?.backend === "canvas2d",
    simulate_adapter_failure,
    force_fallback_adapter,
    JSON.stringify(initial_horizontal_domain),
  ).catch((error: unknown) => {
    for (const canvas of [gpu_pane, fallback_pane, plugin_canvas, overlay]) canvas.remove();
    if (assigned_relative_position) container.style.position = previous_container_position;
    throw error;
  });
  let chart: chart_impl | null = null;
  try {
    // Default style settings first (theme.ts), explicit options second — the engine deep-merges
    // successive patches, so caller options always win over the theme palette. `theme`,
    // `handle_scroll`, `handle_scale`, `kinetic_scroll`, `tracking_mode`, backend selection/test
    // flags, and `layout.panes.enableResize` are package-level keys and are not forwarded to the
    // engine's options store (gestures/backend ownership live entirely in TS/WASM host code).
    const { theme, initialPane, handle_scroll, handle_scale, kinetic_scroll, wheel_behavior, price_axis_wheel_zoom, tracking_mode, localization, accessibility, ...rest } =
      (options ?? {}) as deep_partial<chart_options> & {
        tracking_mode?: tracking_mode_options;
      };
    // IANA time-zone names resolve in the package; the engine receives explicit schedules.
    const exchange = split_exchange_time_options(rest as Record<string, unknown>);
    let engine_options: Record<string, unknown> = { ...exchange.engine };
    delete engine_options.backend;
    delete engine_options.__simulate_webgpu_adapter_failure;
    delete engine_options.__force_webgpu_fallback_adapter;
    let panes_resize: boolean | undefined;
    const panes = (rest.layout as { panes?: { enableResize?: boolean } } | undefined)?.panes;
    if (panes?.enableResize !== undefined) {
      const { enableResize, ...panes_rest } = panes;
      engine_options = { ...engine_options, layout: { ...(rest.layout as object), panes: panes_rest } };
      panes_resize = enableResize;
    }
    const selected_theme = (theme ?? default_theme_name) as theme_name;
    // Named theme helpers carry package-level identity for live apply_options/reset semantics. The
    // engine only receives the palette projection, never the package-only `theme` key.
    wasm.apply_options(JSON.stringify(theme_options(theme_palette(selected_theme))));
    if (Object.keys(engine_options).length > 0) {
      wasm.apply_options(JSON.stringify(engine_options));
    }
    const auto_size = options?.autoSize === true;
    chart = new chart_impl(
      wasm,
      container,
      gpu_pane,
      fallback_pane,
      plugin_canvas,
      overlay,
      auto_size,
      selected_theme,
      initialPane !== undefined && initial_horizontal_domain.type !== "financial_time",
    );
    if (
      handle_scroll !== undefined || handle_scale !== undefined || kinetic_scroll !== undefined ||
      tracking_mode !== undefined
    ) {
      chart.apply_gesture_options(handle_scroll, handle_scale, kinetic_scroll, tracking_mode);
    }
    if (
      exchange.zone !== undefined || exchange.session_start !== undefined ||
      exchange.tick_marks !== undefined || exchange.bar_time_label !== undefined
    ) {
      chart.apply_exchange_time(exchange.zone, exchange.session_start, exchange.tick_marks, exchange.bar_time_label);
    }
    if (wheel_behavior !== undefined) chart.apply_options({ wheel_behavior });
    if (price_axis_wheel_zoom !== undefined) chart.apply_options({ price_axis_wheel_zoom });
    if (panes_resize !== undefined) {
      chart.apply_panes_resize(panes_resize);
    }
    if (localization !== undefined) {
      // deep_partial recurses into the callback signatures; the fields are already optional, so the
      // concrete localization_options shape is what apply_localization expects.
      chart.apply_localization(localization as localization_options);
    }
    if (accessibility !== false) {
      enable_accessibility(
        chart,
        accessibility === undefined || accessibility === true
          ? {}
          : accessibility as accessibility_options,
      );
    }
    chart.render();
    return chart;
  } catch (error) {
    if (chart !== null) {
      chart.remove();
    } else {
      wasm.dispose();
      wasm.free();
      for (const canvas of [gpu_pane, fallback_pane, plugin_canvas, overlay]) canvas.remove();
    }
    if (assigned_relative_position) container.style.position = previous_container_position;
    throw error;
  }
}

/** Camel-case alias of {@link create_chart}; both return the same chart API. */
export const createChart = create_chart;
