// Worker-safe OffscreenCanvas façade. This module deliberately avoids window, document,
// HTMLElement, ResizeObserver, and DOM events; the owning worker relays normalized input samples.

// @ts-ignore -- pkg is generated by build:wasm.
import { create_offscreen_chart as wasm_create_offscreen_chart, AerisChart } from "../pkg/aeris_charts_wasm.js";

import {
  apply_series_time_alignment, assert_live_series, ensure_init, normalize_time_tick_marks, time_to_utc_seconds,
  validate_series_time_alignment,
} from "./impl.js";
import { route_wheel, wheel_speed_adjustment } from "./gestures.js";
import { AerisChartsError } from "./errors.js";
import { default_theme_name, theme_options, theme_palette, type theme_name } from "./theme.js";
import { exchange_time_json, split_exchange_time_options } from "./time_zone.js";
import { FEATURE_KIND_TO_U8, KIND_TO_U8, is_feature_series_kind, is_footprint_series_kind } from "./types.js";
import type {
  any_series_options,
  backend_status,
  chart_options,
  deep_partial,
  frame_stats,
  footprint_bar,
  footprint_trade,
  footprint_trade_columns,
  ingestion_diagnostics,
  ohlc_columns,
  series_kind,
  series_data,
  series_merge_columns,
  series_options,
  series_update_options,
  time_zone,
} from "./types.js";

const FRAME_STATS_SLOT = {
  cpu_ms: 0,
  gpu_ms: 1,
  draw_calls: 2,
  dropped_frames: 3,
  presented_frames: 4,
  memory_bytes: 5,
  canvas2d_ops: 6,
  ring_overruns: 7,
  gpu_buffer_allocations: 8,
  gpu_write_calls: 9,
  gpu_uploaded_bytes: 10,
  layout_rebuilds: 11,
  autoscale_runs: 12,
  series_rebuilds: 13,
  drawing_rebuilds: 14,
  grid_rebuilds: 15,
  overlay_rebuilds: 16,
  axis_rebuilds: 17,
  text_resolutions: 18,
  trading_rebuilds: 19,
  ring_dropped_rows: 20,
} as const;

const UNSUPPORTED_WORKER_OPTIONS = [
  "autoSize",
  "localization",
  "handle_scroll",
  "handle_scale",
  "kinetic_scroll",
  "tracking_mode",
  "accessibility",
] as const;

type offscreen_layout_options = Omit<deep_partial<chart_options["layout"]>, "panes"> & {
  panes?: Omit<deep_partial<chart_options["layout"]["panes"]>, "enableResize">;
};

/** Engine-owned options supported by a worker chart. DOM gestures, localization callbacks,
 * ResizeObserver sizing, and pane-separator dragging stay on the DOM `create_chart` façade. */
export type offscreen_chart_options = Omit<
  deep_partial<chart_options>,
  (typeof UNSUPPORTED_WORKER_OPTIONS)[number] | "layout"
> & { layout?: offscreen_layout_options };

/** The series options a worker chart can change after creation: how a series' timestamps land on
 * the shared time axis (`series_options.time_alignment`, `series_options.as_of_max_staleness`). */
export type offscreen_series_options = Partial<Pick<series_options, "time_alignment" | "as_of_max_staleness">>;

function split_offscreen_options(options: offscreen_chart_options): {
  theme: "light" | "dark" | undefined;
  wheel_behavior: "auto" | "pan" | "zoom" | undefined;
  engine: Record<string, unknown>;
  zone: time_zone | undefined;
  session_start: number | undefined;
  tick_marks: unknown;
  bar_time_label: unknown;
} {
  const raw = options as Record<string, unknown>;
  for (const key of UNSUPPORTED_WORKER_OPTIONS) {
    if (key in raw) throw new AerisChartsError("unsupported_operation", `worker charts do not support option ${key}`);
  }
  const layout = raw.layout as { panes?: Record<string, unknown> } | undefined;
  if (layout?.panes && "enableResize" in layout.panes) {
    throw new AerisChartsError(
      "unsupported_operation",
      "worker charts do not support option layout.panes.enableResize",
    );
  }
  const { theme, wheel_behavior, ...engine } = options;
  // Declarative `timeScale.timeZone` (IANA name or schedule), `timeScale.sessionStart`,
  // `timeScale.tickMarks`, and `timeScale.barTimeLabel` resolve here with the worker's own `Intl`;
  // the engine receives an explicit schedule, UTC-second mark times, and the label to validate
  // together with the session start.
  const exchange = split_exchange_time_options(engine as Record<string, unknown>);
  return {
    theme,
    wheel_behavior,
    engine: exchange.engine,
    zone: exchange.zone,
    session_start: exchange.session_start,
    tick_marks: exchange.tick_marks,
    bar_time_label: exchange.bar_time_label,
  };
}

/** Apply resolved exchange-time options and explicit time-axis marks; throws `invalid_options`
 * without changing anything. */
function apply_offscreen_exchange_time(
  wasm: AerisChart,
  zone: time_zone | undefined,
  session_start: number | undefined,
  tick_marks: unknown,
  bar_time_label: unknown,
): void {
  if (
    zone === undefined && session_start === undefined && tick_marks === undefined &&
    bar_time_label === undefined
  ) return;
  const marks = tick_marks === undefined ? undefined : normalize_time_tick_marks(tick_marks);
  const reason = wasm.set_exchange_time_json(exchange_time_json(zone, session_start, marks, bar_time_label));
  if (reason !== "") throw new AerisChartsError("invalid_options", reason);
}

export interface offscreen_chart_init {
  /** Chart media size in CSS pixels. Workers cannot infer this from a transferred canvas. */
  width: number;
  height: number;
  /** Explicit device-pixel ratio used for both backing stores and engine geometry. */
  dpr: number;
  options?: offscreen_chart_options;
  /** Initial kind for the construction-time primary series (default `candlestick`). */
  series_kind?: series_kind;
  /** Test/runtime hook matching the DOM constructor's deterministic fallback path. */
  force_fallback_adapter?: boolean;
}

export interface offscreen_pointer_event {
  type: "down" | "move" | "up" | "cancel" | "leave";
  /** Full-chart media coordinates, not bitmap coordinates. */
  x: number;
  y: number;
  pointer_id?: number;
  button?: number;
  buttons?: number;
  ctrl_key?: boolean;
  meta_key?: boolean;
  shift_key?: boolean;
  pointer_type?: "mouse" | "touch" | "pen";
  timestamp_ms?: number;
  pressure?: number;
  tilt_x?: number;
  tilt_y?: number;
}

export interface offscreen_wheel_event {
  /** Full-chart media coordinates. */
  x: number;
  y: number;
  delta_x: number;
  delta_y: number;
  /** 0 = pixels, 1 = lines, 2 = pages (the WheelEvent values). */
  delta_mode?: 0 | 1 | 2;
  /** Ctrl (or `meta_key`, macOS Cmd) zooms around the pointer instead of pinning the right edge. */
  ctrl_key?: boolean;
  shift_key?: boolean;
  meta_key?: boolean;
}

export interface offscreen_key_event {
  key: string;
  ctrl_key?: boolean;
  shift_key?: boolean;
  meta_key?: boolean;
}

/**
 * A chart hosted entirely in a worker. It intentionally exposes the allocation-free typed data
 * path and normalized input injection rather than DOM-only APIs (accessibility, HTML plugins,
 * synchronous screenshots, and ResizeObserver sizing).
 */
export class offscreen_chart {
  private readonly stats_scratch = new Float64Array(AerisChart.frame_stats_len());
  private readonly input_scratch = new Float64Array(AerisChart.input_update_len());
  private readonly backend_change_handlers = new Set<(backend: "webgpu" | "canvas2d") => void>();
  private primary_adopted = false;
  private drag_pointer_id: number | null = null;
  private pinch_active = false;
  private last_ingestion: ingestion_diagnostics | null = null;
  private removed = false;
  private width: number;
  private height: number;
  private dpr: number;
  private last_backend: "webgpu" | "canvas2d";
  private readonly backend_loss_handler: EventListener;
  /** Host clock (UTC seconds) for the countdown; `null` uses the system clock. */
  private clock: (() => number) | null = null;
  /** Per-series calendar-date input form of structured feature data. */
  private readonly calendar_series = new Map<number, boolean>();
  private calendar_date_axis = false;

  constructor(
    private readonly wasm: AerisChart,
    private readonly gpu_canvas: OffscreenCanvas,
    private readonly fallback_canvas: OffscreenCanvas,
    width: number,
    height: number,
    dpr: number,
    private wheel_behavior: "auto" | "pan" | "zoom",
    private selected_theme: theme_name = default_theme_name,
  ) {
    this.width = width;
    this.height = height;
    this.dpr = dpr;
    this.last_backend = this.wasm.backend_kind() as "webgpu" | "canvas2d";
    // Device-loss dispatch can occur while a wasm export still owns `AerisChart`; defer re-entry
    // so wasm-bindgen's recursive-use guard cannot trip.
    this.backend_loss_handler = () => {
      // Rendering performs the actual state transition, then notifies the owner so it can reveal
      // the already-warm fallback HTML canvas.
      queueMicrotask(() => {
        if (!this.removed) this.render();
      });
    };
    globalThis.addEventListener("aeris_charts-chart-backend-lost", this.backend_loss_handler);
  }

  backend(): "webgpu" | "canvas2d" {
    this.assert_live();
    return this.wasm.backend_kind() as "webgpu" | "canvas2d";
  }

  /** Structured backend selection/fallback diagnostics for this worker chart. */
  backend_status(): Readonly<backend_status> {
    this.assert_live();
    return Object.freeze(JSON.parse(this.wasm.backend_status_json()) as backend_status);
  }

  /** Diagnostics for the most recent worker-side data ingestion. */
  last_ingestion_diagnostics(): ingestion_diagnostics | null {
    this.assert_live();
    return this.last_ingestion;
  }

  private record_ingestion(json: string | undefined): boolean {
    this.last_ingestion = json === undefined ? null : JSON.parse(json) as ingestion_diagnostics;
    return this.last_ingestion?.status !== "rejected";
  }

  /** Subscribe to runtime WebGPU → Canvas2D fallback. The owner should reveal the HTML canvas
   * matching `backend`; returns an unsubscribe function. Construction-time backend is available
   * synchronously from {@link backend}. */
  subscribe_backend_change(handler: (backend: "webgpu" | "canvas2d") => void): () => void {
    this.assert_live();
    this.backend_change_handlers.add(handler);
    return () => this.backend_change_handlers.delete(handler);
  }

  /** Adopt the primary series on the first call; later calls append independent series. An
   *  ordinary series takes `time_alignment` and `as_of_max_staleness` from `options`; change them
   *  later with {@link apply_series_options}. */
  add_series(kind: series_kind, options: Partial<any_series_options> = {}): number {
    this.assert_live();
    if (kind === "custom") {
      throw new AerisChartsError("unsupported_operation", "custom series need a DOM host renderer");
    }
    if (is_footprint_series_kind(kind)) {
      const id = this.wasm.add_footprint_series(!this.primary_adopted, JSON.stringify(options));
      this.primary_adopted = true;
      if (id === 0xffffffff) {
        throw new AerisChartsError("invalid_options", "footprint series options were rejected by the engine");
      }
      this.render();
      return id;
    }
    if (is_feature_series_kind(kind)) {
      const id = this.wasm.add_feature_series(
        FEATURE_KIND_TO_U8[kind],
        !this.primary_adopted,
        JSON.stringify(options),
      );
      this.primary_adopted = true;
      if (id === 0xffffffff) {
        throw new AerisChartsError("invalid_options", `advanced series '${kind}' was rejected by the engine`);
      }
      this.render();
      return id;
    }
    // Ordinary worker series take their calendar alignment at creation (`time_alignment`). Bad
    // values are refused before a series is created or the primary adopted: a worker host has no
    // handle to remove a leaked series with.
    validate_series_time_alignment(options);
    const adopted = !this.primary_adopted;
    const adopted_kind = adopted ? this.wasm.series_kind(0) : undefined;
    let id = 0;
    if (adopted) {
      this.primary_adopted = true;
      this.wasm.set_series_type(KIND_TO_U8[kind]);
    } else {
      id = this.wasm.add_series(KIND_TO_U8[kind]);
    }
    try {
      apply_series_time_alignment(this.wasm, id, options);
    } catch (error) {
      // An engine refusal leaves no series behind either.
      if (adopted) {
        this.primary_adopted = false;
        if (adopted_kind !== undefined) this.wasm.set_series_type(adopted_kind);
      } else {
        this.wasm.remove_series_tracked(id);
      }
      throw error;
    }
    this.render();
    return id;
  }

  /**
   * Change a series' `time_alignment` and `as_of_max_staleness` after creation, exactly as
   * `series.apply_options` does on the main thread (an omitted key keeps its value, switching to
   * `"union"` clears the staleness bound, a request equal to the current values is a no-op).
   * `series_id` is the id `add_series` returned (0 is the primary). Nothing is applied when the
   * call throws: `disposed`, `invalid_handle` or `stale_handle` for an id that names no live
   * series (even for an empty patch), `invalid_options` for a bad value or a non-object patch, and
   * `unsupported_operation` for a series without its own calendar or for any other series option,
   * which a worker chart cannot change after creation. A call that succeeds repaints the canvas
   * before it returns (an unchanged request too), one that throws paints nothing. A worker chart
   * has no series handles and so no `subscribe_data_changed` notification; read
   * `visible_logical_range()` after the call.
   */
  apply_series_options(options: offscreen_series_options, series_id = 0): void {
    this.assert_live();
    assert_live_series(this.wasm, series_id);
    if (typeof options !== "object" || options === null) {
      throw new AerisChartsError("invalid_options", "series options must be an object");
    }
    for (const [key, value] of Object.entries(options)) {
      if (value !== undefined && key !== "time_alignment" && key !== "as_of_max_staleness") {
        throw new AerisChartsError(
          "unsupported_operation",
          `worker charts cannot change series option ${key} after creation`,
        );
      }
    }
    apply_series_time_alignment(this.wasm, series_id, options);
    this.render();
  }

  /** A snapshot of a series' current options as the engine reports them (`series_id` as in
   *  {@link apply_series_options}). Throws like it for an id that names no live series. */
  series_options(series_id = 0): Readonly<series_options> {
    this.assert_live();
    assert_live_series(this.wasm, series_id);
    return Object.freeze(JSON.parse(this.wasm.series_options_json(series_id)) as series_options);
  }

  /** Replace a series' columns. `options.sequence` installs the snapshot's sequence guard
   *  baseline; a replace without one clears it (see `series_update_options`). */
  set_data_typed(columns: ohlc_columns, series_id = 0, options?: series_update_options): void {
    this.assert_live();
    if (this.wasm.series_kind(series_id) === 7 || this.wasm.series_kind(series_id) === 8) {
      throw new AerisChartsError(
        "unsupported_operation",
        "set_data_typed() does not apply to structured advanced-series payloads",
      );
    }
    const sequence = this.sequence_argument(options);
    if (sequence === null) return;
    if (!this.record_ingestion(this.wasm.set_series_data_typed(
      series_id, columns.times, columns.open, columns.high, columns.low, columns.close,
    ))) return;
    this.note_calendar(series_id, columns.times.length === 0 ? null : false);
    if (!Number.isNaN(sequence)) this.wasm.set_series_update_sequence(series_id, sequence);
    this.render();
  }

  /** Stream a typed batch. `options.sequence` rejects a stale batch (see `series_update_options`). */
  update_typed(columns: ohlc_columns, series_id = 0, options?: series_update_options): void {
    this.assert_live();
    if (this.wasm.series_kind(series_id) === 7 || this.wasm.series_kind(series_id) === 8) {
      throw new AerisChartsError(
        "unsupported_operation",
        "update_typed() does not apply to structured advanced-series payloads",
      );
    }
    const sequence = this.sequence_argument(options);
    if (sequence === null) return;
    if (!this.record_ingestion(Number.isNaN(sequence)
      ? this.wasm.update_series_bars_typed(
        series_id, columns.times, columns.open, columns.high, columns.low, columns.close,
      )
      : this.wasm.update_series_bars_typed_sequenced(
        series_id, columns.times, columns.open, columns.high, columns.low, columns.close, sequence,
      ))) return;
    if (columns.times.length > 0) this.note_calendar_update(series_id, false);
    this.render();
  }

  /** Merge partial typed rows (see `series_api.merge_typed`): `NaN` entries and omitted columns
   *  keep the bar's values; the batch is rejected atomically. */
  merge_typed(columns: series_merge_columns, series_id = 0, options?: series_update_options): void {
    this.assert_live();
    if (this.wasm.series_kind(series_id) === 7 || this.wasm.series_kind(series_id) === 8) {
      throw new AerisChartsError(
        "unsupported_operation",
        "merge_typed() does not apply to structured advanced-series payloads",
      );
    }
    const sequence = this.sequence_argument(options);
    if (sequence === null) return;
    if (!this.record_ingestion(this.wasm.merge_series_bars_typed(
      series_id, columns.times, columns.open, columns.high, columns.low, columns.close, sequence,
    ))) {
      // Stale deliveries are expected under a sequence guard; any other drop is never silent.
      if (this.last_ingestion?.code !== "stale_sequence") {
        console.warn(`aeris_charts: merge_typed rejected — ${this.last_ingestion?.reason ?? "invalid data"}`);
      }
      return;
    }
    if (columns.times.length > 0) this.note_calendar_update(series_id, false);
    this.render();
  }

  /** `NaN` encodes "no sequence"; an invalid sequence records a rejection and returns `null`. */
  private sequence_argument(options: series_update_options | undefined): number | null {
    const sequence = options?.sequence;
    if (sequence === undefined) return NaN;
    if (Number.isSafeInteger(sequence) && sequence >= 0) return sequence;
    console.warn("aeris_charts: sequence must be a non-negative safe integer");
    this.last_ingestion = {
      status: "rejected",
      accepted: 0,
      dropped_invalid: 0,
      dropped_non_finite: 0,
      dropped_out_of_range: 0,
      deduplicated: 0,
      reordered: false,
      semantic_anomalies: 0,
      reason: "sequence must be a non-negative safe integer",
    };
    return null;
  }

  /** Replace structured data for a Rust-native advanced series in a worker chart. */
  set_feature_data(data: readonly series_data[], series_id = 0): void {
    this.assert_live();
    const converted = data.map((item) => ({ ...item, time: time_to_utc_seconds(item.time) }));
    if (!this.record_ingestion(this.wasm.set_feature_series_data(series_id, converted))) return;
    this.note_calendar(series_id, data.length === 0 ? null : data.every((item) => typeof item.time !== "number"));
    this.render();
  }

  /** Append or replace one structured advanced-series row in a worker chart. */
  update_feature(item: series_data, series_id = 0): void {
    this.assert_live();
    if (!this.record_ingestion(this.wasm.update_feature_series_item(
      series_id,
      { ...item, time: time_to_utc_seconds(item.time) },
    ))) return;
    this.note_calendar_update(series_id, typeof item.time !== "number");
    this.render();
  }

  /** Typed columns are numeric instants; business-day feature data marks calendar dates. */
  private note_calendar(series_id: number, calendar: boolean | null): void {
    if (calendar === null) this.calendar_series.delete(series_id);
    else this.calendar_series.set(series_id, calendar);
    let axis = this.calendar_series.size > 0;
    for (const value of this.calendar_series.values()) axis &&= value;
    if (axis !== this.calendar_date_axis) {
      this.calendar_date_axis = axis;
      this.wasm.set_calendar_date_axis(axis);
    }
  }

  /** A streamed row: one numeric instant makes the series instant-based. */
  private note_calendar_update(series_id: number, calendar: boolean): void {
    const current = this.calendar_series.get(series_id);
    if (current === undefined) this.note_calendar(series_id, calendar);
    else if (current && !calendar) this.note_calendar(series_id, false);
  }

  /**
   * Install (or with `null` remove) the host clock used by the candle-close countdown. It returns
   * UTC seconds and is read on every render instead of the worker's `Date.now()`.
   */
  set_clock(clock: (() => number) | null): void {
    this.assert_live();
    if (clock !== null && typeof clock !== "function") {
      throw new AerisChartsError("invalid_options", "set_clock expects a function returning UTC seconds, or null");
    }
    this.clock = clock;
    if (clock === null) this.wasm.set_now_seconds(Number.NaN);
    this.render();
  }

  set_footprint_trades_typed(columns: footprint_trade_columns, series_id = 0): void {
    this.assert_live();
    const result = this.wasm.set_footprint_trades_typed(
      series_id,
      columns.timestamps_micros,
      columns.prices,
      columns.volumes,
      columns.aggressors,
      columns.bids,
      columns.asks,
      columns.sequences,
      columns.trade_ids,
      columns.conditions,
      columns.session_ids,
    );
    if (result !== "") throw new AerisChartsError("invalid_data", result);
    this.render();
  }

  update_footprint_trades_typed(
    columns: footprint_trade_columns,
    series_id = 0,
  ): "tip" | "historical" {
    this.assert_live();
    const result = this.wasm.update_footprint_trades_typed(
      series_id,
      columns.timestamps_micros,
      columns.prices,
      columns.volumes,
      columns.aggressors,
      columns.bids,
      columns.asks,
      columns.sequences,
      columns.trade_ids,
      columns.conditions,
      columns.session_ids,
    );
    if (result !== "tip" && result !== "historical") {
      throw new AerisChartsError("invalid_data", result);
    }
    this.render();
    return result;
  }

  update_footprint_trade(trade: footprint_trade, series_id = 0): "tip" | "historical" {
    this.assert_live();
    const side = trade.aggressor === "buy" ? 1 : trade.aggressor === "sell" ? 2 : 0;
    const result = this.wasm.update_footprint_trade_typed(
      series_id,
      trade.timestamp_micros,
      trade.price,
      trade.volume,
      side,
      trade.bid ?? Number.NaN,
      trade.ask ?? Number.NaN,
      trade.sequence ?? Number.NaN,
      trade.trade_id ?? Number.NaN,
      trade.conditions ?? 0,
      trade.session_id ?? Number.NaN,
    );
    if (result !== "tip" && result !== "historical") {
      throw new AerisChartsError("invalid_data", result);
    }
    this.render();
    return result;
  }

  footprint_bars(series_id = 0): readonly footprint_bar[] {
    this.assert_live();
    return JSON.parse(this.wasm.footprint_bars_json(series_id)) as footprint_bar[];
  }

  apply_options(options: offscreen_chart_options): void {
    this.assert_live();
    const { theme, wheel_behavior, engine, zone, session_start, tick_marks, bar_time_label } =
      split_offscreen_options(options);
    apply_offscreen_exchange_time(this.wasm, zone, session_start, tick_marks, bar_time_label);
    if (wheel_behavior !== undefined) this.wheel_behavior = wheel_behavior;
    if (theme !== undefined) {
      this.selected_theme = theme;
      this.wasm.apply_options(JSON.stringify(theme_options(theme_palette(theme))));
    }
    if (Object.keys(engine).length > 0) this.wasm.apply_options(JSON.stringify(engine));
    this.render();
  }

  /** Restore canonical Aeris visual defaults for the currently selected theme without resetting
   * data, scale/view state, or advanced-series semantics. */
  reset_style_to_defaults(): void {
    this.assert_live();
    this.wasm.reset_style_to_defaults(this.selected_theme === "light");
    this.render();
  }

  fit_content(): void {
    this.assert_live();
    this.wasm.fit_content();
    this.render();
  }

  resize(width: number, height: number, dpr = this.dpr): void {
    this.assert_live();
    this.width = Math.max(width, 1);
    this.height = Math.max(height, 1);
    this.dpr = Math.max(dpr, Number.EPSILON);
    const bitmap_width = Math.max(1, Math.round(this.width * this.dpr));
    const bitmap_height = Math.max(1, Math.round(this.height * this.dpr));
    this.gpu_canvas.width = bitmap_width;
    this.gpu_canvas.height = bitmap_height;
    this.fallback_canvas.width = bitmap_width;
    this.fallback_canvas.height = bitmap_height;
    this.wasm.resize(this.width, this.height, this.dpr);
    this.render();
  }

  render(): void {
    this.assert_live();
    if (this.clock !== null) {
      // A non-finite or throwing host clock falls back to the system clock (NaN unpins the
      // engine clock), matching the main-thread chart instead of freezing the last value.
      let now = Number.NaN;
      try {
        now = this.clock();
      } catch (error) {
        console.error("aeris_charts: offscreen host clock threw", error);
      }
      this.wasm.set_now_seconds(Number.isFinite(now) ? now : Number.NaN);
    }
    this.wasm.render();
    const backend = this.backend();
    if (backend !== this.last_backend) {
      this.last_backend = backend;
      for (const handler of this.backend_change_handlers) {
        try {
          handler(backend);
        } catch (error) {
          console.error("aeris_charts: offscreen backend-change handler threw", error);
        }
      }
    }
  }

  /**
   * Inject a normalized pointer sample relayed from the host. Primary-pointer drags pan the time
   * scale; hover/move drives the crosshair. Axis coordinates are accepted but do not begin a pan.
   */
  inject_pointer_event(event: offscreen_pointer_event): void {
    this.assert_live();
    const id = event.pointer_id ?? 1;
    const x = event.x - this.wasm.pane_left();
    const y = event.y;
    const pane_width = this.wasm.time_scale_width();
    const pane_height = this.height - this.wasm.time_scale_height();
    const in_pane = x >= 0 && x <= pane_width && y >= 0 && y <= pane_height;
    const primary = (event.button ?? 0) === 0;
    const device = event.pointer_type === "touch" ? 1 : event.pointer_type === "pen" ? 2 : 0;
    const target = in_pane ? 0 : y > pane_height ? 4 : 3;
    const feed = (phase: "down" | "move" | "up") => {
      const method = phase === "down" ? this.wasm.input_pointer_down.bind(this.wasm)
        : phase === "move" ? this.wasm.input_pointer_move.bind(this.wasm)
          : this.wasm.input_pointer_up.bind(this.wasm);
      const modifiers = (event.shift_key ? 1 : 0) | (event.ctrl_key ? 2 : 0)
        | (event.meta_key ? 8 : 0);
      method(
        id, device, target, modifiers, x, y, event.timestamp_ms ?? performance.now(),
        event.pressure ?? (primary ? 0.5 : 0), event.tilt_x ?? 0, event.tilt_y ?? 0,
        this.input_scratch,
      );
      return {
        kind: this.input_scratch[0]!,
        pointer_id: this.input_scratch[2]!,
        x: this.input_scratch[5]!,
        y: this.input_scratch[6]!,
        previous_x: this.input_scratch[7]!,
        scale_delta: this.input_scratch[9]!,
      };
    };

    switch (event.type) {
      case "down":
        if (!primary) return;
        {
          const update = feed("down");
          if (update.kind === 11) return;
          if (update.kind === 5) {
            if (this.drag_pointer_id !== null) this.wasm.scroll_end();
            this.drag_pointer_id = null;
            this.pinch_active = true;
            this.wasm.scroll_start(update.x);
          } else if (in_pane && this.drag_pointer_id === null) {
            this.wasm.scroll_start(x);
            this.drag_pointer_id = id;
            this.wasm.set_crosshair(x, y);
          }
        }
        break;
      case "move":
        {
          const update = feed("move");
          if (update.kind === 6) {
            this.wasm.scroll_move(update.x);
            if (update.scale_delta !== 0) {
              // Pinching is direct manipulation: it stays anchored at the pinch point even though
              // wheel zoom pins the right edge.
              this.wasm.zoom_focused(update.x, this.wasm.pinch_zoom_scale(update.scale_delta));
            }
          } else if (this.drag_pointer_id === id) {
            this.wasm.scroll_move(x);
          }
        }
        if (in_pane || this.drag_pointer_id === id) this.wasm.set_crosshair(x, y);
        else this.wasm.clear_crosshair();
        break;
      case "up": {
        const update = feed("up");
        if (update.kind === 7) {
          this.wasm.scroll_end();
          this.wasm.scroll_start(update.x);
          this.drag_pointer_id = update.pointer_id;
          this.pinch_active = false;
        } else if (this.drag_pointer_id === id || this.pinch_active) {
          this.wasm.scroll_end();
          this.drag_pointer_id = null;
          this.pinch_active = false;
        }
        break;
      }
      case "cancel":
        this.wasm.input_cancel_all(this.input_scratch);
        if (this.drag_pointer_id !== null || this.pinch_active) this.wasm.scroll_end();
        this.drag_pointer_id = null;
        this.pinch_active = false;
        break;
      case "leave":
        if (this.drag_pointer_id !== id) this.wasm.clear_crosshair();
        break;
    }
    this.render();
  }

  /** Inject a relayed wheel sample through the same router as the DOM recognizer. Worker charts
   *  expose no `handle_scroll`/`handle_scale` options, so both wheel gestures stay enabled. */
  inject_wheel_event(event: offscreen_wheel_event): void {
    this.assert_live();
    const delta_mode = event.delta_mode ?? 0;
    route_wheel(
      this.wasm,
      {
        delta_x: event.delta_x,
        delta_y: event.delta_y,
        delta_mode,
        ctrl_key: event.ctrl_key === true,
        shift_key: event.shift_key === true,
        meta_key: event.meta_key === true,
        speed: wheel_speed_adjustment(delta_mode, this.dpr),
        point: () => ({ x: event.x - this.wasm.pane_left(), y: event.y }),
      },
      { wheel_behavior: this.wheel_behavior, wheel_zoom: true, wheel_scroll: true },
    );
    this.render();
  }

  /** Inject the keyboard subset that has deterministic worker semantics. */
  inject_key_event(event: offscreen_key_event): boolean {
    this.assert_live();
    const step = event.ctrl_key || event.shift_key ? 10 : 1;
    const center = this.wasm.time_scale_width() / 2;
    let handled = true;
    switch (event.key) {
      case "ArrowLeft":
        this.wasm.scroll_to_position(this.wasm.scroll_position() - step);
        break;
      case "ArrowRight":
        this.wasm.scroll_to_position(this.wasm.scroll_position() + step);
        break;
      case "+":
      case "=":
        this.wasm.zoom(center, 0.5);
        break;
      case "-":
      case "_":
        this.wasm.zoom(center, -0.5);
        break;
      case "Home":
        this.wasm.fit_content();
        break;
      case "Delete":
      case "Backspace":
        handled = this.wasm.remove_selected_drawing();
        break;
      case "Escape":
        this.wasm.clear_crosshair();
        break;
      default:
        handled = false;
    }
    if (handled) this.render();
    return handled;
  }

  visible_logical_range(): { from: number; to: number } | null {
    this.assert_live();
    const range = this.wasm.visible_logical_range();
    return range.length === 2 ? { from: range[0]!, to: range[1]! } : null;
  }

  frame_stats(): frame_stats {
    this.assert_live();
    const out = this.stats_scratch;
    this.wasm.frame_stats_into(out);
    const gpu_ms = out[FRAME_STATS_SLOT.gpu_ms] as number;
    return {
      cpu_ms: out[FRAME_STATS_SLOT.cpu_ms] as number,
      gpu_ms: Number.isNaN(gpu_ms) ? null : gpu_ms,
      draw_calls: out[FRAME_STATS_SLOT.draw_calls] as number,
      dropped_frames: out[FRAME_STATS_SLOT.dropped_frames] as number,
      presented_frames: out[FRAME_STATS_SLOT.presented_frames] as number,
      memory_bytes: out[FRAME_STATS_SLOT.memory_bytes] as number,
      canvas2d_ops: out[FRAME_STATS_SLOT.canvas2d_ops] as number,
      ring_overruns: out[FRAME_STATS_SLOT.ring_overruns] as number,
      gpu_buffer_allocations: out[FRAME_STATS_SLOT.gpu_buffer_allocations] as number,
      gpu_write_calls: out[FRAME_STATS_SLOT.gpu_write_calls] as number,
      gpu_uploaded_bytes: out[FRAME_STATS_SLOT.gpu_uploaded_bytes] as number,
      layout_rebuilds: out[FRAME_STATS_SLOT.layout_rebuilds] as number,
      autoscale_runs: out[FRAME_STATS_SLOT.autoscale_runs] as number,
      series_rebuilds: out[FRAME_STATS_SLOT.series_rebuilds] as number,
      drawing_rebuilds: out[FRAME_STATS_SLOT.drawing_rebuilds] as number,
      grid_rebuilds: out[FRAME_STATS_SLOT.grid_rebuilds] as number,
      overlay_rebuilds: out[FRAME_STATS_SLOT.overlay_rebuilds] as number,
      axis_rebuilds: out[FRAME_STATS_SLOT.axis_rebuilds] as number,
      text_resolutions: out[FRAME_STATS_SLOT.text_resolutions] as number,
      trading_rebuilds: out[FRAME_STATS_SLOT.trading_rebuilds] as number,
      ring_dropped_rows: out[FRAME_STATS_SLOT.ring_dropped_rows] as number,
    };
  }

  remove(): void {
    if (this.removed) return;
    globalThis.removeEventListener("aeris_charts-chart-backend-lost", this.backend_loss_handler);
    if (this.drag_pointer_id !== null) this.wasm.scroll_end();
    this.wasm.input_cancel_all(this.input_scratch);
    this.drag_pointer_id = null;
    this.pinch_active = false;
    this.backend_change_handlers.clear();
    this.removed = true;
    this.wasm.dispose();
    this.wasm.free();
  }

  private assert_live(): void {
    if (this.removed) throw new AerisChartsError("disposed", "offscreen chart has been removed");
  }
}

/**
 * Construct a worker chart from two transferred canvases. The caller should display only the
 * canvas matching `chart.backend()`; two surfaces preserve runtime Canvas2D fallback without
 * rebuilding chart state.
 */
/** @experimental Worker/offscreen hosting is not part of the frozen stable surface. */
export async function create_offscreen_chart(
  gpu_canvas: OffscreenCanvas,
  fallback_canvas: OffscreenCanvas,
  init: offscreen_chart_init,
): Promise<offscreen_chart> {
  await ensure_init();
  const width = Math.max(init.width, 1);
  const height = Math.max(init.height, 1);
  const dpr = Math.max(init.dpr, Number.EPSILON);
  const options = init.options ?? {};
  const { theme, wheel_behavior, engine: engine_options, zone, session_start, tick_marks, bar_time_label } =
    split_offscreen_options(options);
  const wasm = await wasm_create_offscreen_chart(
    gpu_canvas,
    fallback_canvas,
    width,
    height,
    dpr,
    options.backend === "canvas2d",
    false,
    init.force_fallback_adapter === true,
  );
  const selected_theme = theme ?? default_theme_name;
  wasm.apply_options(JSON.stringify(theme_options(theme_palette(selected_theme))));
  if (Object.keys(engine_options).length > 0) {
    wasm.apply_options(JSON.stringify(engine_options));
  }
  try {
    apply_offscreen_exchange_time(wasm, zone, session_start, tick_marks, bar_time_label);
  } catch (error) {
    wasm.dispose();
    wasm.free();
    throw error;
  }
  const initial_kind = init.series_kind ?? "candlestick";
  if (initial_kind === "footprint") {
    if (wasm.add_footprint_series(true, "{}") === 0xffffffff) {
      throw new AerisChartsError("invalid_options", "default footprint series was rejected");
    }
  } else {
    wasm.set_series_type(KIND_TO_U8[initial_kind]);
  }
  const chart = new offscreen_chart(
    wasm, gpu_canvas, fallback_canvas, width, height, dpr, wheel_behavior ?? "auto", selected_theme,
  );
  chart.render();
  return chart;
}
